[package]
name = "server-playground"
version = "0.1.0"
authors = ["David Lenfesty <lenfesty@ualberta.ca>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rusqlite = "0.16.0"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["json", "serve"]